/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 1
 * Build: 1.0.0
 * Runtime: browser:javascript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

/**
 * @typedef BaseEvent
 * @type {object}
 * @property {string} event_type
 * @property {Object.<string, *>} [event_properties]
 */

/**
 * @typedef Plan
 * @type {object}
 * @property {string} [branch]
 * @property {string} [source]
 * @property {string} [version]
 * @property {string} [versionId]
 */

/**
 * @typedef LoadClientOptions
 * @type {object}
 * @property {string} [apiKey]
 * @property {Object} [configuration]
 * @property {BrowserClient} [instance]
 */

/**
 * @typedef LoadOptions
 * @type {object}
 * @property {'mindersvetdev'} [environment]
 * @property {boolean} [disabled]
 * @property {LoadClientOptions} [client]
 */

/**
 * @typedef {Object} EventOptions
 * @type {object}
 */

/**
 * @typedef ApiKey
 * @type {object}
 * @property {string} mindersvetdev
 */
export const ApiKey = {
  mindersvetdev: 'a1f05bb4175a983fae715b80c85bc5ad'
};

/**
 * @typedef {Object} DistributorInfo
 * @param {string} [distributor_city] Ciudad del distribuidor
 * @param {string} distributor_name Nombre del distribuidor
 * @param {number} [distributor_store_id] Store id asignado
 * @param {string} [distributor_zone] Zona de despacho
 */

/**
 * @typedef {Object} ProductInfo
 * @param {string} distribuitor_id Id del distribuidor
 * @param {string} distribuitor_name Nombre de distribuidor
 * @param {number} price Precio
 * @param {string} product_id Product id
 * @param {string} product_name Nombre de producto
 */

/**
 * @typedef {Object} StatusInfo
 * @param {boolean} is_approved Aprobación de distribuidor
 * @param {string} reason Razon de respuesta de aprobación
 */

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration = {
  plan: {
    version: '1',
    branch: 'develop',
    source: 'web',
    versionId: '5dcfc9eb-5e25-4ff4-a782-48aa984f00af'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-javascript-ampli',
      sourceVersion: '2.0.0'
    }
  }
};

export class AccountCreated {
  constructor() {
    this.event_type = 'Account Created';
  }
}

export class AccountCreationStarted {
  constructor() {
    this.event_type = 'Account Creation Started';
  }
}

export class CheckoutViewed {
  constructor() {
    this.event_type = 'Checkout Viewed';
  }
}

export class CuitAdded {
  constructor() {
    this.event_type = 'CUIT Added';
  }
}

export class DistribuitorApproved {
  constructor(properties) {
    this.event_type = 'Distribuitor Approved';
    this.event_properties = properties;
  }
}

export class DistributorSelected {
  constructor() {
    this.event_type = 'Distributor Selected';
  }
}

export class DocumentAdded {
  constructor() {
    this.event_type = 'Document Added';
  }
}

export class OrderPlaced {
  constructor() {
    this.event_type = 'Order Placed';
  }
}

export class ProductAddedToCart {
  constructor(properties) {
    this.event_type = 'Product Added to Cart';
    this.event_properties = properties;
  }
}

export class ProductViewed {
  constructor(properties) {
    this.event_type = 'Product Viewed';
    this.event_properties = properties;
  }
}

export class ProffesionalNumberAdded {
  constructor() {
    this.event_type = 'Proffesional Number Added';
  }
}

export class UserLoggedIn {
  constructor() {
    this.event_type = 'User Logged In';
  }
}

export class UserLoggedOut {
  constructor() {
    this.event_type = 'User Logged Out';
  }
}

/**
 * @typedef PromiseResult
 * @type {object}
 * @property {Promise|undefined} promise
 */

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  constructor() {
    /* @type {BrowserClient|undefined} */
    this.amplitude = undefined;
    this.disabled = false;
  }

  /**
   * @return {BrowserClient}
   */
  get client() {
    this.isInitializedAndEnabled();
    return this.amplitude;
  }

  /**
   * @return {boolean}
   */
  get isLoaded() {
    return this.amplitude != null;
  }

  /**
   * @private
   * @return {boolean}
   */
  isInitializedAndEnabled() {
    if (!this.isLoaded) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param {LoadOptions} options Configuration options to initialize the Ampli SDK with. 'environment', 'client.apiKey' or 'client.instance' is required.
   *
   * @return {PromiseResult}
   */
  load(options) {
    this.disabled = options?.disabled ?? false;

    if (this.isLoaded) {
      console.warn('WARNING: Ampli is already initialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey;
    if (options?.client?.apiKey) {
      apiKey = options.client.apiKey;
    } else if (options?.environment) {
      apiKey = ApiKey[options.environment];
    }

    if (options?.client?.instance) {
      this.amplitude = options?.client?.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...options?.client?.configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user.
   *
   * @param {string|undefined} userId The user's id.
   * @param {EventOptions} [options] Optional event options.
   *
   * @return {PromiseResult}
   */
  identify(userId, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options, user_id: userId};
    }

    const ampIdentify = new amplitude.Identify();
    return this.amplitude.identify(ampIdentify, options);
  }

  /**
  * Flush the event.
  */
  flush() {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude.flush();
  }

  /**
   * Track event
   *
   * @param {BaseEvent} event The event to track.
   * @param {EventOptions} [options] Optional event options.
   *
   * @return {PromiseResult}
   */
  track(event, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude.track(event, undefined, options);
  }

  /**
   * Account Created
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Account%20Created)
   *
   * Confirmación de datos y crear Cuenta
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  accountCreated(options) {
    return this.track(new AccountCreated(), options);
  }

  /**
   * Account Creation Started
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Account%20Creation%20Started)
   *
   * Clic en el botón crear cuenta
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  accountCreationStarted(options) {
    return this.track(new AccountCreationStarted(), options);
  }

  /**
   * Checkout Viewed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Checkout%20Viewed)
   *
   * Ver checkout
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  checkoutViewed(options) {
    return this.track(new CheckoutViewed(), options);
  }

  /**
   * CUIT Added
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/CUIT%20Added)
   *
   * Se agregó número para información tributaria
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  cuitAdded(options) {
    return this.track(new CuitAdded(), options);
  }

  /**
   * Distribuitor Approved
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Distribuitor%20Approved)
   *
   * El distribuidor aprueba
   *
   * @param {Object} properties The event's properties.
   * @param {string} [properties.distributor_city] Ciudad del distribuidor
   * @param {string} properties.distributor_name Nombre del distribuidor
   * @param {number} [properties.distributor_store_id] Store id asignado
   * @param {string} [properties.distributor_zone] Zona de despacho
   * @param {boolean} properties.is_approved Aprobación de distribuidor
   * @param {string} properties.reason Razon de respuesta de aprobación
   * @param {EventOptions} [options] Options for this track call.
   */
  distribuitorApproved(properties, options) {
    return this.track(new DistribuitorApproved(properties), options);
  }

  /**
   * Distributor Selected
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Distributor%20Selected)
   *
   * Selección del distribuidor
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  distributorSelected(options) {
    return this.track(new DistributorSelected(), options);
  }

  /**
   * Document Added
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Document%20Added)
   *
   * Documento adjuntado validación matrícula profesional o habilitación sanitaria
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  documentAdded(options) {
    return this.track(new DocumentAdded(), options);
  }

  /**
   * Order Placed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Order%20Placed)
   *
   * Confirmación de la orden
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  orderPlaced(options) {
    return this.track(new OrderPlaced(), options);
  }

  /**
   * Product Added to Cart
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Product%20Added%20to%20Cart)
   *
   * Agregar producto al carrito
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.distribuitor_id Id del distribuidor
   * @param {string} properties.distribuitor_name Nombre de distribuidor
   * @param {number} properties.price Precio
   * @param {string} properties.product_id Product id
   * @param {string} properties.product_name Nombre de producto
   * @param {EventOptions} [options] Options for this track call.
   */
  productAddedToCart(properties, options) {
    return this.track(new ProductAddedToCart(properties), options);
  }

  /**
   * Product Viewed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Product%20Viewed)
   *
   * Ver producto
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.distribuitor_id Id del distribuidor
   * @param {string} properties.distribuitor_name Nombre de distribuidor
   * @param {number} properties.price Precio
   * @param {string} properties.product_id Product id
   * @param {string} properties.product_name Nombre de producto
   * @param {EventOptions} [options] Options for this track call.
   */
  productViewed(properties, options) {
    return this.track(new ProductViewed(properties), options);
  }

  /**
   * Proffesional Number Added
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/Proffesional%20Number%20Added)
   *
   * Se agregó número de matrícula profesional del veterinario
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  proffesionalNumberAdded(options) {
    return this.track(new ProffesionalNumberAdded(), options);
  }

  /**
   * User Logged In
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/User%20Logged%20In)
   *
   * Inicio de sesión
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  userLoggedIn(options) {
    return this.track(new UserLoggedIn(), options);
  }

  /**
   * User Logged Out
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/MindersVet%20-%20Dev/events/develop/latest/User%20Logged%20Out)
   *
   * Cerrar sesión
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  userLoggedOut(options) {
    return this.track(new UserLoggedOut(), options);
  }
}

export const ampli = new Ampli();
